export { WebRTCStore, DEFAULT_RELAYS } from './store.js';
export { Peer } from './peer.js';
export {
  PeerSelector,
  peerPrincipal,
  normalizeDispatchConfig,
  buildHedgedWavePlan,
  syncSelectorPeers,
} from './peerSelector.js';
export {
  PeerId,
  generateUuid,
  WEBRTC_KIND,
  MAX_HTL,
  HtlMode,
  type HtlPolicy,
  BLOB_REQUEST_POLICY,
  MESH_EVENT_POLICY,
  MESH_PROTOCOL,
  MESH_PROTOCOL_VERSION,
  MESH_DEFAULT_HTL,
  MESH_MAX_HTL,
  PEER_METADATA_SNAPSHOT_VERSION,
  MSG_TYPE_REQUEST,
  MSG_TYPE_RESPONSE,
  FRAGMENT_SIZE,
  createMeshNostrEventFrame,
  validateMeshNostrFrame,
  parseMeshNostrFrameText,
  type SignalingMessage,
  type MeshNostrFrame,
  type MeshNostrPayload,
  type WebRTCStoreConfig,
  type PeerStatus,
  type WebRTCStoreEvent,
  type WebRTCStoreEventHandler,
  type EventSigner,
  type EventEncrypter,
  type EventDecrypter,
  type GiftWrapper,
  type GiftUnwrapper,
  type SignedEvent,
  type PeerPool,
  type PeerClassifier,
  type PoolConfig,
  type SelectionStrategy,
  type RequestDispatchConfig,
  type PersistedPeerMetadata,
  type PeerMetadataSnapshot,
  type MeshStats,
  type WebRTCStats,
  type BandwidthSample,
  type DataRequest,
  type DataResponse,
} from './types.js';

// Protocol functions
export {
  encodeRequest,
  encodeResponse,
  parseMessage,
  createRequest,
  createResponse,
  createFragmentResponse,
  hashToKey,
  verifyHash,
  generatePeerHTLConfig,
  decrementHTLWithPolicy,
  decrementHTL,
  shouldForwardHTL,
  shouldForward,
  type PeerHTLConfig,
  type PendingRequest,
} from './protocol.js';
